/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData bookmark = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData writesong = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData writesong_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_audio = IconData(0xf1c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
